### ISSUE TITLE
how can i use another version jquery library with natural_js

### ISSUE THREAD

**Issue by lemonfish** [bbalganjjm/natural_js#28]
i need to use latest jquery library for third party library dependency.
thanks.

**Comment by bbalganjjm** [comment]
Import jquery-1.12.4.min.js first, then load Natural-JS related libraries as follows.
Then import another version of JQuery.


<script type="text/javascript" charset="utf-8" src="js/natural_js/lib/jquery-1.12.4.min.js"></script>

<script type="text/javascript" charset="utf-8" src="js/natural_js/natural.js.min.js"></script>
<script type="text/javascript" charset="utf-8" src="js/natural_js/natural.template.min.js"></script>
<script type="text/javascript" charset="utf-8" src="js/natural_js/natural.code.js"></script>
<script type="text/javascript" charset="utf-8" src="js/natural_js/natural.config.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


However, if an error occurs when using the functions provided by Natural-JS with the $() function, you should use the N() function.
Based on the example above, the $() function works with jQuery version 3.5.1 and N() works with the 1.12.4 version.

You can also completely isolate jQuery 3.5.1 version by using the jQuery.noConflict function.
