### ISSUE TITLE
select 바인드 오류.

### ISSUE THREAD

**Issue by kimBS731** [bbalganjjm/natural_js#32]
ds_chlDvn:[{
"cd_id":"",
"cd_nm":"전체"
},{
"cd_id":"1",
"cd_nm":"val1"
},{
"cd_id":"2",
"cd_nm":"val2"
},{
"cd_id":"3",
"cd_nm":"val3"
},{
"cd_id":"4",
"cd_nm":"val4"
},{
"cd_id":"5",
"cd_nm":"val5"
},{
"cd_id":"6",
"cd_nm":"val6"
}
]

으로 생성후
N(cont.ds_chlDvn).select(N("#chlDvn",view)).bind();
작업 후 실행시

시스템오류가 발생했습니다.

라는 오류 alert이 뜸.

**Comment by bbalganjjm** [comment]
테스트 결과 프레임웍 자체의 이상은 없는 것 같습니다.

예측건데 XX생명보험의 Natural-JS AOP 를 처리하는 모듈(aopProc.js)쪽에 인자 개수(7개)를 체크하여 공통코드를 불러와 셀렉트 컴포넌트를 자동으로 생성 해 주는 로직이 있습니다. 해당 로직을 살펴 봐야 할 것 같습니다.
일단 cont 의 ds_chlDvn 의 변수 이름이나 #chlDvn 요소의 id 값을 변경 하고 다시 시도 해 보시기 바랍니다.

현장에 있는 개발자에게도 지원을 부탁 해 놓았으니 연락이 갈 겁니다.
